project_id = "jvgmuzcrtvtabfoiqltg"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[db]
port = 54322

[inbucket]
enabled = true
port = 54324

[storage]

[edge_runtime]

[analytics]
enabled = false

[functions."admin-payment-settings"]
verify_jwt = true

[functions.paystack-public-key]
verify_jwt = false

[functions.paystack-initialize]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false